---
abstract: 'Regex DispatchType'
author:
  - unknown
build_requires: {}
configure_requires:
  Module::Build: 0.4004
dynamic_config: 1
generated_by: 'Module::Build version 0.4004, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Catalyst-DispatchType-Regex
provides:
  Catalyst::DispatchType::LocalRegex:
    file: lib/Catalyst/DispatchType/LocalRegex.pm
  Catalyst::DispatchType::LocalRegexp:
    file: lib/Catalyst/DispatchType/LocalRegexp.pm
  Catalyst::DispatchType::Regex:
    file: lib/Catalyst/DispatchType/Regex.pm
    version: 5.90033
  Catalyst::DispatchType::Regexp:
    file: lib/Catalyst/DispatchType/Regexp.pm
requires:
  Moose: 0
  Text::Balanced: 0
  Text::SimpleTable: 0
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Catalyst-DispatchType-Regex
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mvgrimes/catalyst-dispatch-regex
version: 5.90033
x_test_requires:
  Data::Dumper: 0
  MRO::Compat: 0
  Scalar::Util: 0
  Test::More: 0
  namespace::autoclean: 0
